### PR TITLE
Added service file for systemd in script/systemd/brimir.service.

### PR DESCRIPTION
**Pull request by thehunt33r**
Hi !

I wrote a service file for systemd. Do you think it would be a good addition ?

Thanks !

### CODE REVIEW

**Comment by frenkel** [comment]
Thank you! If you rename it to `passenger-brimir` and make the hardcoded directory `/root/brimir/` configurable it might be usefull indeed.

**Comment by thehunt33r** [comment]
Do you think we could use an environment variable ? Maybe something like $brimir_path ?

Also, I've written an [ansible role](https://github.com/thehunt33r/ansible-role-brimir) where the systemd file is a template, and then gets written according to the user's specifications. This is why the path was hardcoded at first.

**Comment by frenkel** [comment]
I'm not familiar with systemd yet, but I don't think systemd will know about that environment variable when the computer boots.

Great work on the ansible task!

**Comment by thehunt33r** [comment]
Yes indeed you're right ! Well, maybe we could leave a placeholder in the file and instruct the user to use a sed -i command to replace the placeholder according to his configuration ? These files can't be much more customizable than that.

Thanks !

**Comment by frenkel** [comment]
Is it not possible to load a variable from /etc/default/brimir? Just like how the puppet agent init scripts can be configured?

**Comment by thehunt33r** [comment]
Hi !

I just pushed an update. Indeed, I made the service file load $BRIMIR_PATH from /etc/default/brimir . That should work without any problem.

**Comment by frenkel** [comment]
Yes, if you add that, I'll merge it.

**Comment by thehunt33r** [comment]
Done.

I also have included an example file (brimir.example).

**Comment by frenkel** [comment]
Thanks!

**Pull request merged**
