### PR TITLE
dataTable for tickets table

### PR DESCRIPTION
**Pull request by mpakus**
+ now it has header for sort
+ pagination
+ quick search
and looks like this http://monosnap.com/image/ONzcOuuQ2w5ijpc5XxUkJ0nfmAjey3

### CODE REVIEW

**Comment by frenkel** [comment]
Looks good, thanks! Why are there two search boxes on the same page?

Also, I can't merge your commit because it has conflicts with `master`. Could you rebase on our `master`?

**Comment by mpakus** [comment]
I finished with rebase.

and about "search", I think need to check first which one is better for search and leave one. What do you think?

**Comment by frenkel** [comment]
Seems to work quite well with a few rows, but when the number of ticket grows beyond 100 it gets slower and near 500 it's almost unusable. Could this also be made to work with ajax to load and filter?

**Comment by mpakus** [comment]
yeah, nice idea! I will do it with ajax!

**Comment by frenkel** [comment]
@mpakus do you need any help?

**Comment by mpakus** [comment]
thanks, no. was busy little bit, but this weeks is free and I will try to finish what I have started. I will commit new pull request.

**Comment by frenkel** [comment]
No problem, a new pull request is the best way indeed. Make sure you base it on current `master`, because we've made quite some changes :-)

**Comment by mpakus** [comment]
of course I will do rebase :+1:

**Pull request closed without merging**
