### PR TITLE
Time consumed

### PR DESCRIPTION
**Pull request by stricte**

### CODE REVIEW

**Comment by frenkel** [comment]
Wouldn't it be better to add a collection of "hours consumed" to a ticket, where you can also track when the hours were made, with an additional note describing what was done?

**Comment by stricte** [comment]
Hi,

From my point of view at this stage this info isnt needed. We need total
time which we consumed. Also i dont see purpose od keeping that details in
db.
All up to you.
16 lut 2015 16:53 "Frank Groeneveld" <notifications@github.com> napisał(a):

**Comment by frenkel** [comment]
Will you be using this yourself? Our company normally tracks time in a different tool where we keep the time when we did something and a description of what we did as well.

**Comment by stricte** [comment]
Yes. I will leave this functionality in this form in my fork. We do not
care when sth has happen.

**Comment by frenkel** [comment]
Ok, no problem. Thanks for the pull request though :-)

I've merged the CSV time format bugfix, but the other commits are not functional enough for us to merge. The first 3 and last 2 seem like configuration errors in your development environment instead of changes that should be in the main repo.

**Pull request closed without merging**
