### PR TITLE
Add users crud to api

### PR DESCRIPTION
**Pull request by bsylvain**
This allow to create users from the API. It also allow to see ticket assigned to one users. To allow the use of the email as the identifier in an API request to see a user, it is encoded in base 64 (@ is not supposed to be used for path in an URL).

### CODE REVIEW

**Comment by bsylvain** [comment]
I am not sure why it submitted all of my commits for ticket creation that are already merged with master

**Comment by frenkel** [comment]
Thanks for the PR!
The commits probably show up because you did not create a new branch from our master. Could you try to do that? Otherwise the commit history will be quite messy

**Comment by bsylvain** [comment]
I am looking on how to do a correct PR.

**Comment by frenkel** [comment]
I think it would be the simplest way to do a rebase on our repo. Something like this (untested, make a backup!):
```
git remote add upstream https://github.com/ivaldi/brimir
git fetch upstream
git checkout <your branch>
git rebase upstream/master
```
You'll then have to force-push (dangerous! could lose commits) it to github.

**Comment by frenkel** [comment]
I can try it if you can't get it to work.

**Comment by frenkel** [comment]
I've done the rebase for you, all changes are now in master. The easiest way to start afresh with new changes is removing and forking the ivaldi/brimir repo again.

Thanks for you contribution!

**Comment by bsylvain** [comment]
Sorry for the mess, i tried the rebase but I was not sure about the commit that i did not made. I am pretty sure my problem comes from that I started to update this new branch with the master and my create ticket branch before the ticket branch integration into the master. Lesson learned.

**Pull request closed without merging**
