### PR TITLE
Create status replies when ticket is assigned or closed.

### PR DESCRIPTION
**Pull request by fiedl**
I'm not sure if you would like to have this in the main project. Please feel free to just close this pull request. But we've added this to our production instance recently.

### What's new?

* Users can have a `name`. If no name is given, take "foo" from "foo@example.com" of their `email`.
* If a ticket is assigned, send a reply to the user: *"Foo is working on your request, now."* (*Foo* is the `name` of the agent.)
* If a ticket is closed, send a reply to the user: *"Your support ticket has been closed. If the issue is not resolved, yet, please feel free to reply. For new requests, please send a separate email. Thanks!"*

### Why?

We had some cases where agents self-assigned a ticket, then needed several days to research and did not reply to the ticket's user in that time. That's a bad habit. Ideally, the agents should be urged to reply early and tell the client that they need time to research. But this is a quick hack to let the user know that someone is working on his problem.

We also had some cases where someone closed tickets without any reply or internal comment. And, we did not know, who did it. With this addition, we (1) can see in the reply history, who closed a ticket; and (2) the client sees when his ticket is closed and can reply if it has been closed unjustified.

### Caveats

Currently, the new behavior is default. Maybe, this should be configurable and opt-in before merging it into master.

### CODE REVIEW

**Comment by frenkel** [comment]
This is great, we've had this requested before as well. Could you make it a configurable checkbox in the tentans edit screen? I'll then merge it directly!

Thanks again,

**Comment by fiedl** [comment]
Ok. Would you expect the status replies to be counted in tickets#index?

bildschirmfoto 2016-06-13 um 10 12 02

To exclude those replies from the counting, we would need something to identify the status replies, for example `Reply.where(status_reply: true)` (analogue to `internal: true`) or `Reply.where(type: "StatusReply")` (as STI).

**Comment by frenkel** [comment]
We ourselves use that indication to see whether the customer knows that we received the message correctly: when there is no reply count, somebody still needs to answer that we'll take a look at his/her problem. So for us it is not a problem to have the count included.

**Comment by fiedl** [comment]
I've added the setting as `Tenant#notify_client_when_ticket_is_assigned_or_closed`.

Before merging we have to consider another thing: Suppose, a new ticket is created. Someone assigns the ticket and, thereby, a status reply is created. When the agent then replies to the ticket, the quoted text is actually the status reply:

bildschirmfoto 2016-06-13 um 22 45 34

It does not matter to us, because we are using the [conversation view](https://github.com/ivaldi/brimir/pull/216), which does not include any quoted text in the answer. I.e. for us, the text field is empty when answering.

But you have to decide if this is the expected behaviour.

**Comment by frenkel** [comment]
Good point. Maybe we do need that reply types, so that we can filter these status notifications and instead quote the latest actual reply (or the ticket itself).

**Comment by fiedl** [comment]
Status replies are now `StatusReply < Reply` (https://github.com/ivaldi/brimir/pull/282/commits/f9e461182511546feb89a9b3b61e22180f4b7960). This way, one can exclude them from quoting (https://github.com/ivaldi/brimir/pull/282/commits/4dea24ae7048cfd459c0108e4531efee787f8846).

I also added a grey background (analogue to the yellow background for internal replies) (https://github.com/ivaldi/brimir/pull/282/commits/648a68865e1a3b71ff279e9a7d2f2ae40b3bd77d).

**Comment by frenkel** [comment]
Thanks! Great work, again. I'll merge it and set the database default to false.

**Pull request merged**
