### PR TITLE
set ticket assignee in create form.

### PR DESCRIPTION
**Pull request by fshahy**
Allow setting assignee in ticket creation form.

### CODE REVIEW

**Comment by fshahy** [comment]
Used same approach as PR 266.

**Comment by frenkel** [comment]
Looks good, but maybe we should not change the default assignee? Currently when an email comes in it is unassigned. I think the form should do the same thing.

**Comment by fshahy** [comment]
OK, fixed it. I did not know that. Still exploring this awesome project.

**Comment by frenkel** [comment]
No problem. I've merged these changes, thank you!

**Pull request merged**
